licenses(["notice"])

package(default_visibility = ['//visibility:public'])

cc_library(
  name = "libaudio",
  srcs = [
    "lame_helper.cc"
  ],
  hdrs = [
    'lame_helper.h',
  ],
  deps = [
    "//third_party/lame:lame",
  ],
)
